/* Reusable journey/reference UI. All game-specific content comes from JOURNEY_DATA. */
window.createGuideCompanion = function ({esc, storageKey, touchSave, navigate, data, openPokemon}) {
  const content=window.JOURNEY_DATA||{quests:[],caps:[],maps:[],references:[]};
  const key=storageKey('journey-v1');
  const clean=raw=>({version:1,completed:[...new Set(Array.isArray(raw?.completed)?raw.completed.filter(x=>content.quests.some(q=>q.id===x)):[])],strata:Math.max(0,Math.min(content.caps.length,Number(raw?.strata)||0)),notes:String(raw?.notes||'').slice(0,20000)});
  let progress;try{progress=clean(JSON.parse(localStorage.getItem(key)||'{}'))}catch{progress=clean({})}
  const save=()=>{localStorage.setItem(key,JSON.stringify(progress));touchSave()};
  let query='',onlyOpen=false,compareIds=[data.pokemon[0]?.id,data.pokemon[1]?.id];
  const heading=(eyebrow,title,description)=>`<header class="page-head"><div><span class="eyebrow">${eyebrow}</span><h1>${title}</h1><p>${description}</p></div></header>`;
  function journey(){
    const quests=content.quests.filter(q=>(!onlyOpen||!progress.completed.includes(q.id))&&`${q.name} ${q.location} ${q.description} ${q.reward}`.toLowerCase().includes(query.toLowerCase()));
    return heading('YOUR EXPEDITION','Adventure journal','Track the Strata, keep field notes, and check off sidequests.')+`<section class="journey-summary"><div><strong>${progress.completed.length}<small> / ${content.quests.length}</small></strong><span>Quests completed</span></div><div><strong>${progress.strata}<small> / ${content.caps.length}</small></strong><span>Strata completed</span></div><div><button class="secondary" data-view="team">Prepare your party →</button></div></section><section class="journal-section"><h2>Into the labyrinth</h2><p>Mark your progress manually. Level caps are source references; optional area and quest prerequisites still apply.</p><label class="progress-select">Completed Strata <select id="journeyStrata">${Array.from({length:content.caps.length+1},(_,i)=>`<option value="${i}" ${i===progress.strata?'selected':''}>${i===0?'Just starting':i+' completed'}</option>`).join('')}</select></label><div class="strata-grid">${content.caps.map((s,i)=>`<article class="${i<progress.strata?'complete':''}"><span>${i<progress.strata?'✓ COMPLETE':'STRATUM '+(i+1)}</span><h3>${esc(s.name.replace(/^.*?Stratum:\s*/,''))}</h3><b>Cap ${s.cap}</b></article>`).join('')}</div></section><section class="journal-section"><h2>Sidequests</h2><div class="journal-filters"><input id="questSearch" type="search" placeholder="Search quests, locations or rewards…" value="${esc(query)}"><label><input id="questOpen" type="checkbox" ${onlyOpen?'checked':''}> Incomplete only</label></div><div id="questResults" class="quest-grid">${quests.map(q=>`<article class="quest-card ${progress.completed.includes(q.id)?'complete':''}"><label><input type="checkbox" data-quest="${q.id}" ${progress.completed.includes(q.id)?'checked':''}><span><small>QUEST ${esc(q.id)}</small><strong>${esc(q.name)}</strong></span></label><p class="quest-place">${esc(q.location)}</p><p>${esc(q.description)}</p><footer><small>REWARD</small>${esc(q.reward)}</footer></article>`).join('')||'<p>No matching quests.</p>'}</div></section><section class="journal-section"><h2>Field notes</h2><textarea id="fieldNotes" rows="5" placeholder="Plans for your next expedition…">${esc(progress.notes)}</textarea><small>Saved on this device and included in guide exports.</small></section>`;
  }
  function atlas(){return heading('CHART YOUR COURSE','Atlas & field references','Naval routes, gathering tables, shop upgrades, and special battle notes.')+content.maps.map(m=>`<section class="journal-section"><h2>${esc(m.name)}</h2><a href="${esc(m.image)}" target="_blank" rel="noopener"><img class="sea-map" src="${esc(m.image)}" alt="${esc(m.name)}; open at full resolution"></a><p>Tap the map to open it at full size.</p></section>`).join('')+content.references.map(ref=>`<details class="reference-table"><summary>${esc(ref.title)}</summary><div class="table-scroll"><table><tbody>${ref.rows.map(row=>`<tr>${Array.from({length:Math.max(...ref.rows.flatMap(r=>r.cells.map(c=>c.column)))},(_,i)=>`<td>${esc(row.cells.find(c=>c.column===i+1)?.value||'')}</td>`).join('')}</tr>`).join('')}</tbody></table></div></details>`).join('')}
  function available(){
    const gates=['First','Second','Third','Fourth'],known=data.locations.filter(l=>gates.some(g=>l.name===`After the ${g} Stratum`)),unlocked=known.filter(l=>progress.strata>=gates.findIndex(g=>l.name===`After the ${g} Stratum`)+1);
    return heading('DOCUMENTED PROGRESSION','Available by milestone','Naval encounters explicitly gated by completed Strata.')+`<section class="journal-section"><p>Your journal records ${progress.strata} completed Strata. These records establish a Stratum requirement; sailing access and other in-game requirements still apply.</p><button class="secondary" data-view="journey">Update journal progress</button><p>${data.locations.length-known.length} encounter areas have no fully resolved progression gate and are excluded from this list.</p></section>`+unlocked.map(l=>`<section class="journal-section"><h2>Naval exploration · ${esc(l.name)}</h2><div class="caught-list">${[...new Set(l.day.map(e=>e.pokemon))].map(key=>{const p=data.pokemon.find(p=>p.key===key);return p?`<button data-companion-pokemon="${p.id}"><img src="${p.sprite}" alt=""><span>${esc(p.name)}</span></button>`:''}).join('')}</div></section>`).join('')+(!unlocked.length?'<p class="empty">No documented naval milestone has been reached. Update your completed Strata in the journal.</p>':'');
  }
  function compare(){
    const choices=data.pokemon.map(p=>`<option value="${p.id}">${esc(p.name)} · #${p.gameDexId}</option>`).join('');
    return heading('PARTY DECISIONS','Compare Pokémon','Compare exact documented forms before choosing your next partner.')+`<div class="quest-grid">${compareIds.map((id,i)=>{const p=data.pokemon.find(p=>p.id===Number(id))||data.pokemon[0];return `<section class="journal-section"><label>Candidate ${i+1}<select data-compare="${i}" aria-label="Candidate ${i+1}">${choices.replace(`value="${p.id}"`,`value="${p.id}" selected`)}</select></label><img width="120" height="120" src="${p.sprite}" alt="${esc(p.name)}"><h2>${esc(p.name)}</h2><p>${p.types.map(esc).join(' / ')} · ${p.bst} BST</p><dl>${['HP','Attack','Defense','Speed','Sp. Atk','Sp. Def'].map((name,n)=>`<div class="compare-stat"><dt>${name}</dt><dd>${p.stats[n]}</dd></div>`).join('')}</dl><p>${p.abilities.map(a=>esc(a.name)).join(' / ')}</p><button class="secondary" data-companion-pokemon="${p.id}">Moves, evolution & acquisition</button></section>`}).join('')}</div>`;
  }
  function coverage(){return heading('ABOUT THIS EDITION','Sources & coverage','Pokémon Odyssey v4.1.1 · Local companion preview')+`<section class="journal-section"><h2>What is documented</h2><p>Pokédex identities, stats, types, level-up moves, encounters, item locations, tutors, quests, Strata caps and Hard Mode rosters come from the developer-linked workbooks. Talrega Dex supplies additional move, ability, evolution and compatibility records.</p><p>The workbooks override conflicting companion data. The sources do not provide a release marker for every field, so exact v4.1.1 alignment remains under review.</p><h3>Difficulty coverage</h3><p>Hard Mode has detailed boss teams. Normal and Picnic boss rosters are not verified. Sea bosses are retained under “Mode unspecified”, never copied into another mode.</p><h3>Known limits</h3><ul><li>Item effects and prices are not yet verified; acquisition information is preserved.</li><li>Some forms have no verified shiny image. The normal sprite is labelled when shown instead.</li><li>Availability filters only use explicit source gates; unknown prerequisites remain unknown.</li><li>Matchup scores are comparative estimates. They do not simulate abilities, held items, EVs, weather or doubles interactions.</li></ul><h3>References</h3><ul>${(window.GUIDE_CONFIG.sources||[]).map(s=>`<li><a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.name)}</a></li>`).join('')}</ul><p>Variant art is extracted from the developer workbook with source-cell and artist attribution retained. Standard sprites use pinned PokéAPI assets. The compass icon is original guide artwork. The cover preview is from <a href="https://www.steamgriddb.com/game/5445119" target="_blank" rel="noopener">SteamGridDB’s Pokémon Odyssey listing</a>; individual artist attribution and full-resolution art remain unverified. Menu icons are Pokémon item sprites from the pinned PokéAPI collection.</p></section>`}
  function home(){return `<section class="adventure-hero"><div><span class="eyebrow">POKÉMON ODYSSEY · V${esc(window.GUIDE_CONFIG.version)}</span><h1>A world below.<br>A journey ahead.</h1><p>Your companion through Talrega and the Yggdrasil Labyrinth. Discover Pokémon, plan your party, and keep every expedition in one place.</p><div class="hero-actions"><button class="primary" data-view="journey">Open your journal →</button><button class="secondary" data-view="pokedex">Explore the Pokédex</button></div><small>FULL REFERENCE · ALL SPOILERS VISIBLE</small></div><figure class="odyssey-cover"><img src="assets/art/odyssey-steamgriddb.jpg" width="267" height="400" alt="Pokémon Odyssey cover featuring its adventurers and Pokémon"><figcaption><a href="https://www.steamgriddb.com/game/5445119" target="_blank" rel="noopener">Artwork via SteamGridDB ↗</a></figcaption></figure></section><section class="metrics"><article><strong>${data.pokemon.length}</strong><span>Documented entries</span></article><article><strong>${data.locations.length}</strong><span>Encounter areas</span></article><article><strong>${content.quests.length}</strong><span>Sidequests</span></article><article><strong>${content.caps.length}</strong><span>Strata to explore</span></article></section><div class="section-title"><span class="eyebrow">PACK YOUR FIELD KIT</span><h2>Where will you go next?</h2></div><section class="feature-grid">${[['pokedex','01','Discover your next partner','Forms, stats, moves and every documented acquisition.'],['team','02','Build a stronger party','Plan current and future teams with complete saved builds.'],['journey','03','Follow your expedition','Strata progress, quest rewards and your own field notes.'],['locations','04','Find it in the wild','Fishing rods, floors, events and encounter rates.'],['battle','05','Prepare for the next fight','Documented boss teams and a custom matchup planner.'],['atlas','06','Chart the waters','Naval map, shop upgrades and gathering references.']].map(([view,n,title,text])=>`<button data-view="${view}"><i>${n}</i><b>${title}</b><span>${text}</span></button>`).join('')}</section><div class="coverage-banner"><span>LOCAL PREVIEW · SOURCE CHECKS IN PROGRESS</span><p>Hard Mode teams are documented. Other difficulties are shown only where the sources establish them.</p><button class="secondary" data-view="coverage">Sources & coverage</button></div>`}
  function bind(root,rerender){
    root.querySelectorAll('[data-companion-pokemon]').forEach(el=>el.onclick=()=>openPokemon(el.dataset.companionPokemon));
    root.querySelectorAll('[data-compare]').forEach(el=>el.onchange=()=>{compareIds[Number(el.dataset.compare)]=Number(el.value);rerender()});
    root.querySelectorAll('[data-quest]').forEach(el=>el.onchange=()=>{progress.completed=el.checked?[...new Set([...progress.completed,el.dataset.quest])]:progress.completed.filter(x=>x!==el.dataset.quest);save();rerender()});
    const strata=root.querySelector('#journeyStrata');if(strata)strata.onchange=()=>{progress.strata=Number(strata.value);save();rerender()};
    const search=root.querySelector('#questSearch');if(search)search.oninput=()=>{query=search.value;rerender()};
    const open=root.querySelector('#questOpen');if(open)open.onchange=()=>{onlyOpen=open.checked;rerender()};
    const notes=root.querySelector('#fieldNotes');if(notes)notes.oninput=()=>{progress.notes=notes.value;save()};
  }
  return {home,journey,atlas,coverage,available,compare,bind,serialize:()=>structuredClone(progress),restore(raw){progress=clean(raw);localStorage.setItem(key,JSON.stringify(progress))}};
};
