import fs from 'node:fs';
import path from 'node:path';
import {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const require=createRequire(path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/','package.json'));
const sharp=require('sharp');
fs.mkdirSync(path.join(root,'assets/icons'),{recursive:true});
for(const size of [32,180,192,512])await sharp(path.join(root,'assets/art/compass.svg')).resize(size,size).png().toFile(path.join(root,`assets/icons/icon-${size}.png`));
const manifest=JSON.parse(fs.readFileSync(path.join(root,'site.webmanifest'),'utf8'));
Object.assign(manifest,{id:'./',name:'Pokémon Odyssey Journal',short_name:'Odyssey',theme_color:'#173c3c',background_color:'#101e20',start_url:'./',scope:'./',display:'standalone',icons:[192,512].map(s=>({src:`assets/icons/icon-${s}.png`,sizes:`${s}x${s}`,type:'image/png',purpose:'any maskable'}))});
fs.writeFileSync(path.join(root,'site.webmanifest'),JSON.stringify(manifest,null,2));
let html=fs.readFileSync(path.join(root,'index.html'),'utf8').replace('<link rel="icon" type="image/svg+xml" href="assets/art/compass.svg">','<link rel="icon" type="image/png" href="assets/icons/icon-32.png">').replace('<link rel="apple-touch-icon" href="assets/art/compass.svg">','<link rel="apple-touch-icon" href="assets/icons/icon-180.png">');
if(!html.includes('register(\'sw.js\')'))html=html.replace('</body>',"<script>if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js');</script></body>");
html=html.replace(/(src|href)="([^"?]+\.(?:js|css))(?:\?[^\"]*)?"/g,(_,attr,file)=>`${attr}="${file}?v=${createHash('sha256').update(fs.readFileSync(path.join(root,file))).digest('hex').slice(0,10)}"`);
fs.writeFileSync(path.join(root,'index.html'),html);
const walk=(dir)=>fs.readdirSync(path.join(root,dir),{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(`${dir}/${e.name}`):[`${dir}/${e.name}`]);
const files=['./','index.html','app.js','companion.js','adventure.css','styles.css','refinements.css','sync-config.js','config/game-config.js','config/game-overrides.js','site.webmanifest',...walk('data').filter(f=>f.endsWith('.js')),...walk('assets'),...Array.from(html.matchAll(/(?:src|href)="([^" ]+\?v=[^"]+)"/g),m=>m[1])];
const cache='odyssey-v411-'+Date.now();
fs.writeFileSync(path.join(root,'sw.js'),`const CACHE=${JSON.stringify(cache)},FILES=${JSON.stringify(files)};self.addEventListener('install',e=>e.waitUntil(caches.open(CACHE).then(c=>c.addAll(FILES)).then(()=>self.skipWaiting())));self.addEventListener('activate',e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith('odyssey-v411-')&&k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));self.addEventListener('fetch',e=>{if(e.request.method!=='GET'||new URL(e.request.url).origin!==self.location.origin)return;e.respondWith(fetch(e.request).then(r=>{if(r.ok){const clone=r.clone();caches.open(CACHE).then(c=>c.put(e.request,clone))}return r}).catch(()=>caches.match(e.request)))});`);
console.log(`Built local app icons and offline cache for ${files.length} files.`);
